### ISSUE TITLE
请问怎么部署到服务器上呢

### ISSUE THREAD

**Issue by GHUserZ** [zimv/nodemailer-demo#1]
请问打包后的怎么部署到服务器上呢

**Comment by zimv** [comment]
把代码拷贝到服务器上 用服务器node命令运行

**Comment by GHUserZ** [comment]
node_modules 也要拷贝到服务器吗

**Comment by zimv** [comment]
直接在服务器上node_modules安装，npm install。

**Comment by GHUserZ** [comment]
使用nginx映射到外网后资源文件404，有遇到过吗大神
